client-reactjs/package-lock.json, client-reactjs/package.json, client-reactjs/src/components/application/JobDetails.js, client-reactjs/src/components/common/MarkdownEditor.js
=> Markdown editor

client-reactjs/src/components/admin/Applications.js, server/routes/app/read.js
fixes #144 
This is a combination of 4 commits.
This is the 1st commit message:
code style
This is the commit message 2:
correct description validation rule regex
This is the commit message 3:
code style
This is the commit message 4:
add validation rule for description input, and return from handleAddAppOk if validation errors exist
=> Description field special characters

client-reactjs/src/components/application/Assets/index.js
in the normal, top-right position of the Assets index component
=> add an "Add Asset" button

client-reactjs/src/components/admin/Applications.js, client-reactjs/src/components/application/FileDetails.js, client-reactjs/src/components/application/FileInstanceDetails.js, client-reactjs/src/components/application/IndexDetails.js, client-reactjs/src/components/application/JobDetails.js, client-reactjs/src/components/application/QueryDetails.js, server/routes/query/read.js
squashed commit messages below:
removing references to setFieldsValue(), validateFields(), and getFieldDecorator() in Applications component
remove references to getFieldDecorator() in FileDetails
remove references to this.props.form methods
package-lock missing from commit that updated antd in package.json
remove validateFields() and setFieldsValue() from FileDetails
removing references to validateFields(), setFieldsValue(), etc
remove setFieldsValue() from JobDetails
=> Fixing form issues after antd update

client-reactjs/src/components/admin/Consumers.js, client-reactjs/src/components/admin/ShareApp.js, client-reactjs/src/components/application/FileDetails.js, client-reactjs/src/components/application/FileInstanceDetails.js, client-reactjs/src/components/application/IndexDetails.js, client-reactjs/src/components/application/JobDetails.js, client-reactjs/src/components/application/QueryDetails.js
onChange property of AutoComplete components should be onSearch in v4 of antd
=> change "onChange" to "onSearch" for AutoComplete components (v4)

client-reactjs/src/index.css
delete selector causing contents of left sidebar to be hidden on narrow width screens
=> fix left sidebar content hidden on narrow width

client-reactjs/src/components/application/FileDetails.js, client-reactjs/src/components/application/IndexDetails.js, client-reactjs/src/components/application/JobDetails.js, client-reactjs/src/components/application/QueryDetails.js, client-reactjs/src/components/common/EditableTable.js, client-reactjs/src/index.css
1. Rich Text description now left-justified
2. Assets > View File > Layout - Changed RegExp  - (/^[a-zA-Z0-9.,:;()?!""@&#*/'_ -]*$/)
3. Table column unexpected behavior on edit mode fixed
=> Worked on UI issues

client-reactjs/src/components/admin/Applications.js, client-reactjs/src/components/application/ApplicationsList.js, server/models/job.js, server/routes/app/read.js, server/routes/user/userservice.js
Backend changes for exporting application, its assets and dataflows to a JSON file
Front end changes for displaying export option in Applications table and to Download the JSON file
=> 208 promoting assets

client-reactjs/package-lock.json, client-reactjs/package.json, client-reactjs/src/components/application/FileDetails.js, client-reactjs/src/components/application/FileTable.js, client-reactjs/src/components/application/IndexTree.js, client-reactjs/src/components/application/QueryTable.js, client-reactjs/src/components/common/EditableTable.js, client-reactjs/src/components/login/ResetPassword.js, server/package-lock.json, server/package.json
removed unused packages/components
=> upgraded react-scripts

client-reactjs/src/components/application/Graph/GraphX6.js
=> fixing sync flow (#403)

client-reactjs/public/assets/i18n/common/en.json
This reverts commit 94e09c360dddd06142695da5bbba5bc83712679b.
=> Revert "Update en.json (#539)"

client-reactjs/src/components/admin/Clusters.jsx, server/routes/hpcc/read.js, server/utils/hpcc-util.js
Adjusted Cluster Timezone Offset to be stored as minutes without floating point to make comparison easier. Also adjusted front end display to reflect changes
=> Adjusted UTC offset storage to minutes

client-reactjs/src/components/admin/Clusters.jsx, client-reactjs/src/components/admin/GitHubSettings/GitHubSettings.js, client-reactjs/src/components/admin/apps/AddApplication.jsx, client-reactjs/src/components/application/clusterMonitoring/ClusterMonitoringNotificationTab.jsx, client-reactjs/src/components/application/clusterMonitoring/ClusterMonitoringTab.jsx, client-reactjs/src/components/application/fileMonitoring/MonitoringTab.jsx, client-reactjs/src/components/application/fileMonitoring/NotificationTab.jsx, client-reactjs/src/components/application/jobMonitoring/JobMonitoringNotificationTab.jsx, client-reactjs/src/components/application/jobMonitoring/JobMonitoringTab.jsx, client-reactjs/src/components/application/superfileMonitoring/MonitoringTab.jsx, client-reactjs/src/components/application/superfileMonitoring/NotificationTab.jsx, client-reactjs/src/components/common/InfoDrawer.jsx, client-reactjs/src/components/userGuides/ApplicationsGuide.jsx, client-reactjs/src/components/userGuides/ClusterGuide.jsx, client-reactjs/src/components/userGuides/CronGuide.jsx, client-reactjs/src/components/userGuides/GithubGuide.jsx, client-reactjs/src/components/userGuides/TeamsWebhookGuide.jsx
Adding user guides to clusters, cron + msteams fields, applications, and github projects.
=> add user guides

client-reactjs/src/components/application/dashboard/ExportMenu/DashboardApiTable.jsx, client-reactjs/src/components/application/dashboard/ExportMenu/DashboardModal.jsx, client-reactjs/src/components/userGuides/ApiKeyGuide.jsx, server/jobs/submitApiKeyMonitoring.js, server/routes/cluster/read.js
Bug Fixes and formatting changes for export options on Dashboard
=> Update API Key and Exports

server/package-lock.json, server/package.json
=> bump semver to 7.5.2

server/routes/notifications/read.js
=> small bug fix

server/package-lock.json, server/package.json
=> Update to nodemailer for dependabot

client-reactjs/src/components/admin/Integrations.js, client-reactjs/src/components/layout/LeftNav.js, server/job-scheduler.js, server/jobs/integrationCreation.js
Adjusted orbit integration name to ASR to better encompass the scope of the integration
=> Adjust Orbit Plugin name to ASR

server/jobSchedularMethods/orbitJobs.js, server/jobs/notifications/notificationsHelperFunctions.js, server/jobs/notifications/processEmailNotifications.js, server/jobs/orbitMegaphone.js, server/migrations/20240119162245-create-notification-queue-table.js, server/models/notification_queue.js, server/notificationTemplates/email/clusterMonitoring.ejs, server/notificationTemplates/email/fileMonitoring.ejs, server/notificationTemplates/email/jobMonitoring.ejs, server/notificationTemplates/email/orbitMonitoring.ejs, server/notificationTemplates/email/superfileMonitoring.ejs, server/notificationTemplates/teams/clusterMonitoring.js, server/notificationTemplates/teams/fileMonitoring.js, server/notificationTemplates/teams/jobMonitoring.js, server/notificationTemplates/teams/orbitMonitoring.js, server/notificationTemplates/teams/superfileMonitoring.js
=> megaphone fix and templateName created

server/migrations/20240404150653-create-directorymonitoring.js, server/models/cluster.js, server/models/directoryMonitoring.js
=> Create model and associations for directory monitorings

server/routes/directorymonitoring/read.js, server/server.js, server/tests/mock-data/directoryMonitoring.json, server/tests/unit/directoryMonitoring.test.js
=> Routes and tests for directory monitoring created

Tombolo/client-reactjs/package-lock.json, Tombolo/client-reactjs/package.json, Tombolo/server/package-lock.json, Tombolo/server/package.json, docs/package-lock.json, docs/package.json
=> bump packages for vulnerabilities

Tombolo/server/package-lock.json, Tombolo/server/package.json, Tombolo/server/routes/cluster/read.js, Tombolo/server/routes/hpcc/read.js, Tombolo/server/routes/notifications/read.js, Tombolo/server/server.js
Verified user input on several routes, as well as added a global XSS sanitizer on our express app to prevent XSS attacks
=> codeql fixes

.github/workflows/deploy-dev-instance-to-azure.yml
=> Added cicd to deploy in azure

Tombolo/server/Dockerfile
=> Python required to install hpcc clinet tools so added to dockerfile

.github/workflows/deploy-asr-instance
=> Asr deploy

.github/workflows/deploy-asr-instance.yml
=> Update and rename deploy-asr-instance to deploy-asr-instance.yml

Tombolo/server/migrations/20240206193030-create-sent-notifications-table.js, Tombolo/server/models/sent_notifications.js
=> Made application ID nullable for sent notification

Tombolo/docker-compose-with-kafka, Tombolo/docker-compose-without-kafka
=> Added line in docker-compose to create volume for cluster  whitelist

Tombolo/client-reactjs/src/App.js, Tombolo/client-reactjs/src/components/layout/Header.js
=> Update guide link on header to open new user documentation site

Tombolo/client-reactjs/src/components/application/home/home.css, Tombolo/client-reactjs/src/components/application/home/index.js
Condense homepage css, remove some padding and break lines so that footer is more easily seen on smaller screen sizes.
Also fixes the footer wrapping bug
=> Home css Fixes

Tombolo/server/config/config.js, Tombolo/server/package.json
Change sequelize so it stores memory of which migrations and seeders have run in custom named tables
=> update sequelize config

Tombolo/server/package.json, docs/docs/Developer/Integrations.md, docs/docs/Developer/_category_.json, docs/docs/Install/Local.md, docs/docs/Install/Uninstall.md, docs/src/components/HomepageGuides/index.js, docs/src/components/HomepageGuides/styles.module.css, docs/src/pages/index.js
=> Uninstall Guide

docs/src/components/HomepageGuides/index.js, docs/src/components/HomepageGuides/styles.module.css
h2 styles for one line were applying globally, adjusting the CSS so it doesn't ruin h2's in other places.
=> Adjust CSS

docs/docs/Install/Docker.md, docs/docs/Install/Env_config.md, docs/docusaurus.config.js
=> Fix links in doc site to allow builds to continue

docs/docusaurus.config.js, docs/src/css/custom.css
Our docs are not sequential so disable pagination globally.
=> Globally disabled pagination

Tombolo/.env.sample, Tombolo/server/controllers/authController.js, Tombolo/server/controllers/sessionController.js, Tombolo/server/middlewares/authMiddleware.js, Tombolo/server/middlewares/sessionMiddleWare.js, Tombolo/server/middlewares/userMiddleware.js, Tombolo/server/migrations/20240927162023-create-password-reset-links-table.js, Tombolo/server/models/PasswordResetLinks.js, Tombolo/server/models/user.js, Tombolo/server/notificationTemplates/email/resetPasswordLink.ejs, Tombolo/server/routes/authRoutes.js, Tombolo/server/routes/sessionRoutes.js, Tombolo/server/routes/userRoutes.js, Tombolo/server/server.js, Tombolo/server/tests/apiTests/auth.test.js, Tombolo/server/tests/apiTests/session.test.js, Tombolo/server/tests/test_server.js
=> additional auth routes and session mgmt routes

Tombolo/server/config/roleTypes.js, Tombolo/server/controllers/authController.js, Tombolo/server/middlewares/rbacMiddleware.js, Tombolo/server/middlewares/tokenValidationMiddleware.js, Tombolo/server/models/user_roles.js, Tombolo/server/routes/clusterRoutes.js, Tombolo/server/routes/sessionRoutes.js, Tombolo/server/routes/userRoutes.js, Tombolo/server/server.js, Tombolo/server/utils/authUtil.js
=> added middleware for granular access control

Tombolo/server/migrations/20241028140603-instance_settings.js, Tombolo/server/models/instance_settings.js
=> Model and Migration

Tombolo/server/jobs/jobMonitoring/monitorIntermediateStateJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobPunctuality.js, Tombolo/server/jobs/jobMonitoring/monitorJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobsUtil.js, Tombolo/server/routes/app/read.js
=> Added fixes to JM not sending alerts;

Tombolo/client-reactjs/src/components/login/ForgotPassword.js, Tombolo/client-reactjs/src/components/login/ResetPassword.js, Tombolo/client-reactjs/src/components/login/ResetTempPw.jsx, Tombolo/client-reactjs/src/components/login/login.js, Tombolo/client-reactjs/src/components/login/registerUserForm.js, Tombolo/client-reactjs/src/index.css
=> CSS fix for login page buttons

Tombolo/client-reactjs/src/components/login/login.js, Tombolo/client-reactjs/src/components/login/register.js, Tombolo/client-reactjs/src/components/login/registerUserForm.js, Tombolo/client-reactjs/src/redux/actions/Auth.js
=> Oauth2 front end

Tombolo/server/jobs/jobMonitoring/monitorIntermediateStateJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobPunctuality.js, Tombolo/server/jobs/jobMonitoring/monitorJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobsUtil.js, Tombolo/server/notificationTemplates/email/jobMonitoring.ejs
Updated date format on Job monitoring notifications. Now it prints in easy-to-read format.
=> formatted date to locale string on job monitoring notifications

Tombolo/client-reactjs/src/components/application/DirectoryMonitoring/AddEditModal/Modal.jsx, Tombolo/client-reactjs/src/components/application/DirectoryMonitoring/AddEditModal/MonitoringTab.jsx
=> Disable Cron and Cron Message from being passed to schedule picker

Tombolo/server/jobSchedularMethods/jobMonitoring.js
=> Corrected JM intervals

Tombolo/client-reactjs/src/components/application/files/FileDetails.js, Tombolo/client-reactjs/src/components/common/AuthHeader.js, Tombolo/client-reactjs/src/components/login/registerUserForm.js, Tombolo/client-reactjs/src/redux/actions/Auth.js, Tombolo/server/controllers/authController.js, Tombolo/server/middlewares/csrfMiddleware.js, Tombolo/server/middlewares/tokenValidationMiddleware.js, Tombolo/server/server.js, Tombolo/server/utils/authUtil.js
=> finish double signed CSRF implementation

Tombolo/client-reactjs/src/components/application/dashboard/notifications/NotificationDashboard.jsx, Tombolo/client-reactjs/src/components/application/dashboard/notifications/NotificationTableFilters.jsx, Tombolo/client-reactjs/src/components/application/dashboard/notifications/UpdateNotification.jsx, Tombolo/client-reactjs/src/components/application/dashboard/notifications/charts/NotificationCountByProductsInGraph.jsx
1. Fixed issue with "Notifications by Product with Status Count" graph not rendering due to nested notification structure changes.
2. Resolved notification update failure by fetching user data from local storage instead of Redux.
3. Added condition to show or hide "Notifications by Product with Status Count" based on ASR presence.
4. Updated keys in notification filter options to resolve non-unique key warnings.
=> Notification graph issue

Tombolo/server/jobSchedular/job-scheduler.js, Tombolo/server/jobSchedularMethods/userManagementJobs.js, Tombolo/server/jobs/userManagement/removeUnverifiedUsers.js
Added a job that runs every 1 hr that removes unverified users older than 24 hours
=> Added a job that cleans up unverified users

Tombolo/client-reactjs/nginx/conf.d/nginx.conf.template-ssl
Updating the conf template for ssl usage. This way when a production (ssl) instance is spun up it uses all the relevant headers.
=> Update nginx.conf template

Tombolo/client-reactjs/src/components/admin/clusters/clusterUtils.js, Tombolo/server/routes/clusterRoutes.js
=> Fix to allow non owners and admins to get clusters

Tombolo/server/controllers/authController.js, Tombolo/server/notificationTemplates/email/accessRequest.ejs, Tombolo/server/notificationTemplates/email/completeRegistration.ejs, Tombolo/server/notificationTemplates/email/resetPasswordLink.ejs, Tombolo/server/notificationTemplates/email/verifyEmail.ejs
URL's should now be properly formatted and hyperlinked in all email templates, as well as a fix for the title of the password reset link email
=> Fixes applied

Tombolo/client-reactjs/src/components/admin/clusters/AddClusterModal.jsx, Tombolo/client-reactjs/src/components/admin/clusters/EditClusterModal.jsx, Tombolo/client-reactjs/src/components/admin/clusters/clusterUtils.js, Tombolo/server/controllers/clusterController.js, Tombolo/server/utils/hpcc-util.js
Changed 401 status code returned by HPCC to 403 before sending it to the client. The client was logging out users when HPCC returned 401
=> Fixed issue caused by 401 status code returned by third party

Tombolo/client-reactjs/src/components/login/login.js, Tombolo/client-reactjs/src/redux/actions/Auth.js
=> Cleaer Password after failed login attempt

Tombolo/server/controllers/userController.js
=> Removed redundant imports

Tombolo/client-reactjs/src/components/login/login.js
Clear only the password input field after a failed login attempt. Leave E-mail address for better UX
=> Clear Only Password Input Field After Invalid Login Attempt

Tombolo/server/controllers/authController.js, Tombolo/server/controllers/userController.js, Tombolo/server/notificationTemplates/email/accountChange.ejs
=>  Send alerts when password or any account information is changed

Tombolo/client-reactjs/src/components/admin/userManagement/Table.jsx, Tombolo/server/controllers/authController.js, Tombolo/server/migrations/20220507024001-create-user.js, Tombolo/server/models/user.js, Tombolo/server/notificationTemplates/email/accountLocked.ejs, Tombolo/server/utils/authUtil.js
=> Lock Account After 5 Invalid Login Attempt

Tombolo/client-reactjs/src/components/admin/userManagement/Table.jsx, Tombolo/client-reactjs/src/components/admin/userManagement/Utils.js, Tombolo/server/controllers/authController.js, Tombolo/server/controllers/userController.js, Tombolo/server/notificationTemplates/email/accountUnlocked.ejs, Tombolo/server/routes/userRoutes.js, Tombolo/server/utils/authUtil.js
=> Flow to Unlock  User's Account

Tombolo/client-reactjs/src/components/login/login.js, Tombolo/client-reactjs/src/redux/actions/Auth.js, Tombolo/server/controllers/authController.js, Tombolo/server/utils/authUtil.js
=> Force User to Change Temp PW - If Attempted to Login With One

Tombolo/client-reactjs/nginx/conf.d/nginx.conf.template-no-ssl, Tombolo/client-reactjs/nginx/conf.d/nginx.conf.template-ssl
=> Added DDoS protection to Nginx config

Tombolo/server/migrations/20250305209301-create-jobMonitoring_data.js, Tombolo/server/migrations/20250305209701-create-jobMonitoring_data_archive.js, Tombolo/server/models/jobMonitoring_data.js, Tombolo/server/models/jobMonitoring_data_archive.js
=> Model and Migration for job monitoring data and archive tables

Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringNotificationTab.jsx
=> Add option for advanced job monitoring

Tombolo/server/jobs/jobMonitoring/monitorIntermediateStateJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobs.js, Tombolo/server/migrations/20250305209301-create-jobMonitoring_data.js, Tombolo/server/migrations/20250305209701-create-jobMonitoring_data_archive.js, Tombolo/server/models/jobMonitoring_data.js, Tombolo/server/models/jobMonitoring_data_archive.js, Tombolo/server/utils/shallowCopyWithoutNested.js
=> Save WuInfo  for  jobs  that needs time series analysis.

Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringNotificationTab.jsx, Tombolo/server/jobs/jobMonitoring/monitorIntermediateStateJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobs.js, Tombolo/server/migrations/20250305209301-create-jobMonitoring_data.js, Tombolo/server/migrations/20250305209701-create-jobMonitoring_data_archive.js, Tombolo/server/models/jobMonitoring_data.js, Tombolo/server/models/jobMonitoring_data_archive.js
=> Added WuState Columns on JM data tables

Tombolo/client-reactjs/src/components/application/jobMonitoring/jobMonitoringUtils.js, Tombolo/server/jobSchedular/job-scheduler.js, Tombolo/server/jobSchedularMethods/jobMonitoring.js, Tombolo/server/jobs/jobMonitoring/fetchWus.js, Tombolo/server/routes/jobmonitoring/read.js
Implemented a Bree job to fetch WU info. Modified the create and patch routes for JM to retrieve WU info when time series analysis is included in the notification condition. Also added front-end code to fetch JM data
=> Implemented a Bree job to fetch WU info

Tombolo/client-reactjs/src/components/application/AppRoutes.js, Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringTable.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/jobMonitoring.css, Tombolo/client-reactjs/src/components/application/jobMonitoring/timeSeriesAnalysis/index.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/timeSeriesAnalysis/timeSeriesFunc.js, Tombolo/client-reactjs/src/index.css, Tombolo/server/jobs/jobMonitoring/fetchWus.js, Tombolo/server/jobs/jobMonitoring/monitorIntermediateStateJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobs.js, Tombolo/server/routes/jobmonitoring/read.js
=> Completed UI for Time Series Analysis

Tombolo/client-reactjs/package-lock.json, Tombolo/client-reactjs/package.json
=> Upgraded http-proxy-middleware

Tombolo/server/package-lock.json, Tombolo/server/package.json
=> Upgraded @hpcc-js/comms to latest version

Tombolo/client-reactjs/package-lock.json, Tombolo/client-reactjs/package.json
=> downgraded http-proxy-middleware

Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringFilters.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringTable.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/SchedulePicker.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/index.jsx
=> Added new filter (JM search input field) to existing JM filters

Tombolo/server/controllers/clusterController.js, Tombolo/server/jobSchedularMethods/clusterJobs.js, Tombolo/server/jobs/cluster/monitorClusterReachability.js, Tombolo/server/jobs/cluster/submitClusterUsageTracker.js
This PR updates cluster tracking and monitoring jobs to align with the new cluster model, replacing legacy metaData fields and adding standardized worker logging.
Added start/end time logging and history trimming in submitClusterUsageTracker.js
Refactored reachability logic in monitorClusterReachability.js to use the new reachabilityInfo field
Updated job scheduler paths for consistency in clusterJobs.js
Simplified controller queries and replaced JSON extraction with direct attributes in clusterController.js
=> Adjusted code to accomodate changes made in cluster model

Tombolo/client-reactjs/src/components/application/myAccount/editAccountActionButton.jsx, Tombolo/client-reactjs/src/components/application/myAccount/myAccount.css, Tombolo/client-reactjs/src/components/application/myAccount/myAccount.jsx, Tombolo/client-reactjs/src/components/application/myAccount/myAccountInfo.jsx, Tombolo/client-reactjs/src/components/application/myAccount/myAccountTable.jsx, Tombolo/client-reactjs/src/components/application/myAccount/utils.js
This PR fixes a crash on the My Account page when user application info is unavailable by removing the applicationStringBuilder utility and its associated form field.
Removed the unused applicationStringBuilder function from utils
Eliminated the import and usage of applicationStringBuilder in the account info component
Updated form layout to occupy full width for roles and cleaned up effect dependencies
=> Fixed my account page crash caused by unaviliablity of user info

Tombolo/client-reactjs/src/components/common/AuthHeader.js, Tombolo/server/middlewares/csrfMiddleware.js, Tombolo/server/utils/authUtil.js
All places where the csrf token header was set or read was updated to no longer check for environment. This means the new token name will always be `x-csrf-token`. The change was made to solve a production issue from nginx with the old header name of `__Host-prod.x-csrf-token`, which I believe was caused by the `.` in the header name. 
NOTE: Also includes eslint auto-fixing.
Fixes #1087 
=> Updated csrf header name to always be `x-csrf-token`

Tombolo/client-reactjs/src/components/application/jobMonitoring/AddEditJobMonitoringModal.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/AsrSpecificMonitoringDetails.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringActionButton.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringTab.jsx
Resolved warning from deprecated apis in antd
=> Resolved warning from depreacted apis in antd

Tombolo/.gitignore, Tombolo/server/server.js, Tombolo/server/utils/readSelfSignedCerts.js, tombolo_docs/docs/Install/Docker.md, tombolo_docs/docs/Install/Local.md, tombolo_docs/docs/User-Guides/self-signed-certs.md
Created customCerts and certs folders.
Created a util that will read custom certificates from the new `customCerts` folder and append them to the new global `http.Agent`. Imported the method in `server.js` and called it so the `http.Agent` is set for all subsequent requests.
Fixes #1088 
=> Support cluster self signed certificates

Tombolo/client-reactjs/src/components/admin/userManagement/ActionButton.jsx, Tombolo/server/controllers/clusterController.js, Tombolo/server/controllers/userController.js, Tombolo/server/middlewares/userMiddleware.js, Tombolo/server/routes/userRoutes.js
Anything related to bulk update of users is commented out because it was not in use. The front end and back end for this action are not wired. We will revisit this later. We might not even need this functionality 
For userController.js:264 throwing user ID does not exist - Made changes so the ID will be  grabbed from the params
CustomError issue - Now correctly grabs the status code from the statusCode
clusterController.js:36 - Added logging and response
=> Issues found during testing

Tombolo/server/package-lock.json, Tombolo/server/package.json, Tombolo/server/server.js
Added the [helmet](https://www.npmjs.com/package/helmet) package. Instantiated the middleware in `server.js`.
Fixes #1098 
=> Added helmet package and instantiated in server.js

Tombolo/server/controllers/clusterController.js, Tombolo/server/utils/hpcc-util.js
Updated usage of auth object in isClusterReachable to be username instead of user. Included timeout in pingCluster.
Fixes #1126 
=> Solved ping cluster 403

Tombolo/server/jobSchedular/job-scheduler.js, Tombolo/server/jobSchedularMethods/apiKeys.js, Tombolo/server/jobSchedularMethods/breeJobs.js, Tombolo/server/jobSchedularMethods/clusterJobs.js, Tombolo/server/jobSchedularMethods/hpccFiles.js, Tombolo/server/jobSchedularMethods/hpccJobs.js, Tombolo/server/jobSchedularMethods/integrationJobs.js, Tombolo/server/jobSchedularMethods/jobMonitoring.js, Tombolo/server/jobSchedularMethods/jobSchedularUtils.js, Tombolo/server/jobSchedularMethods/notificationJobs.js, Tombolo/server/jobSchedularMethods/orbitJobs.js, Tombolo/server/jobSchedularMethods/userManagementJobs.js, Tombolo/server/jobSchedularMethods/workFlowJobs.js, Tombolo/server/jobs/jobMonitoring/monitorJobsTimeSeriesAnalysis.js, Tombolo/server/jobs/jobMonitoring/monitorJobsUtil.js
The monitorJobsTimeSeriesAnalysis function now retrieves the owner of the work unit and called the placeholder function to retrieve the owners email. A placeholder function was created in jobMonitorUtils. These will fully function once we have access to the API to retrieve a users email from their username. `TODO`'s have been added in places that will need updated.
Fixes #1120
=> 1120 owner notification for job tsa

Tombolo/server/seeders/20240312202046-seed-monitoring-types.js
Added new monitoring type to the seeder file to include Landing Zone monitoring
=> Added new monitoring type to the seeder file

Tombolo/server/controllers/statusController.js
Fixed response sent by a route that checks if the instance owner already exists
=> Fixed response sent by a check if owner exists route

.gitignore, Tombolo/client-reactjs/src/components/application/DirectoryMonitoring/AddEditModal/NotificationTab.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringNotificationTab.jsx, Tombolo/client-reactjs/src/components/common/PrimaryContacts.jsx, Tombolo/server/controllers/costMonitoringController.js, Tombolo/server/jobSchedular/job-scheduler.js, Tombolo/server/jobSchedularMethods/costMonitoring.js, Tombolo/server/jobs/costMonitoring/analyzeCostPerUser.js, Tombolo/server/jobs/costMonitoring/monitorCostPerUser.js, Tombolo/server/middlewares/costMonitoringMiddlewares.js, Tombolo/server/migrations/20250626205533-create-cost-monitoring.js, Tombolo/server/migrations/20250626205841-create-cost-monitoring-data.js, Tombolo/server/migrations/20250630131520-create-cost-monitoring-data-totals-view.js, Tombolo/server/models/costMonitoring.js, Tombolo/server/models/costMonitoringData.js, Tombolo/server/models/costMonitoringDataTotals.js, Tombolo/server/notificationTemplates/email/analyzeCostPerUser.ejs, Tombolo/server/package-lock.json, Tombolo/server/package.json, Tombolo/server/routes/costMonitoringRoutes.js, Tombolo/server/seeders/20240312202046-seed-monitoring-types.js, Tombolo/server/server.js
Created routes, middlewares, controllers, models, migrations, and jobs for costMonitoring. 
Fixes #1142 
=> 1129 cost monitoring per user (Backend)

Tombolo/server/controllers/costMonitoringController.js
Added a findByPk in the create controller for cost monitoring. They allows the response to contain the expected creator, updater, etc. fields.
=> Create Cost monitor bug fix

Tombolo/server/package-lock.json, Tombolo/server/package.json
Upgraded hpcc-js-comms package
=> Upgraded hpcc-js/comms to 3.7.6

Tombolo/server/middlewares/asrMiddleware.js, Tombolo/server/middlewares/monitoringMiddleware.js, Tombolo/server/middlewares/notificationQueueMiddleware.js, Tombolo/server/middlewares/notificationsMiddleware.js, Tombolo/server/middlewares/orbitMiddleware.js, Tombolo/server/middlewares/queryMiddleware.js, Tombolo/server/middlewares/reportMiddleware.js, Tombolo/server/middlewares/sentNotificationMiddleware.js, Tombolo/server/middlewares/superfileMonitoringMiddleware.js, Tombolo/server/routes/notification_queue/read.js, Tombolo/server/routes/notifications/email-notification.js, Tombolo/server/routes/notifications/read.js, Tombolo/server/routes/orbit/read.js, Tombolo/server/routes/query/read.js, Tombolo/server/routes/report/read.js, Tombolo/server/routes/sent_notifications/read.js, Tombolo/server/routes/superfilemonitoring/read.js
- Contains a minor bugfix for asrMiddleware.js and monitoringMiddleware.js
- Also the rest of the migrations of validations into middleware files.
Fixes #1139 
This is the final PR for validation cleanup. All (currently used) routes now have their validations extracted to middleware files and their route signatures call the validateRequestBody function to ensure validation is handled at a high level.
=> Validation cleanup 5

Tombolo/server/tests/apiTests/clusterStatusMonitoring.test.js, Tombolo/server/tests/helpers.js, Tombolo/server/tests/setup.js, Tombolo/server/tests/test_server.js
Tests for Cluster  Status Monitoring  API routes
Fixes #1189 
=> Cluster status monitoring API routes tests

Tombolo/client-reactjs/src/components/admin/Integrations/IntegrationSettings.jsx
- Fixed the dynamic import of ASR integration
Fixes issue #1210 
=> Fixed the dynamic import of ASR integration.

Tombolo/server/jobs/lzMonitoring/lzFileCountMonitoring.js
- Fixed bug for cluster association error
- Added name attribute as it is referenced later in the file
=> lzFileCountMonitoring Model Association bugfix

Tombolo/client-reactjs/vite.config.js
Added antd packages to be included in optimizeDeps in `vite.config.js`. Forcing prebundling to esm for internal packages that were commonjs.
Fixes #1251 
=> Dashboard dynamic import errors

Tombolo/client-reactjs/src/components/application/costMonitoring/CostMonitoringActionButton.jsx, Tombolo/server/jobs/costMonitoring/monitorCost.js
- Added `PageSize` to the Workunit query call
- Replaced deprecated prop on popover in CostMonitoringActionButton
=> Added pagesize to workunit query (Cost monitoring)

Tombolo/server/jobs/jobMonitoring/monitorJobPunctuality.js, Tombolo/server/jobs/jobMonitoring/monitorJobs.js, Tombolo/server/jobs/submitOrbitMonitoring.js
Removed hard coded region (USA) from monitoring and dynamically retrieving from asr-domains now
Fixes # 1195
=> Removed hardcoded region and dynamically retreived from asr-domain

Tombolo/server/jobs/archive/archiveData.js, Tombolo/server/jobs/cluster/clusterMonitoring.js, Tombolo/server/jobs/cluster/clustertimezoneoffset.js, Tombolo/server/jobs/cluster/monitorClusterReachability.js, Tombolo/server/tests/breeJobs/archiveData.test.js, Tombolo/server/tests/breeJobs/clusterMonitoring.test.js, Tombolo/server/tests/breeJobs/clustertimezoneoffset.test.js, Tombolo/server/tests/breeJobs/monitorClusterReachability.test.js, Tombolo/server/tests/breeJobs/monitorJobsUtil.test.js, Tombolo/server/tests/setup.js
- Created tests for 
- archiveData
- clusterMonitoring
- clustertimezoneoffset
- clusterReachability
- monitorJobsUtil
- This also included minor updates to the job files to ensure the functions could be exported for testing
- A bug/typo was fixed in archiveData for casing on an import of the CostMonitoringDataArchiveService
Fixes #1269 
=> Bree job tests 2

.github/workflows/codeql-analysis.yml
Upgraded CodeQL action to V3 as V2 is deprecated
Fixes # 1285
=> Upgraded CodeQL action to V3 as V2 is deprecated

Tombolo/client-reactjs/src/components/application/LandingZoneMonitoring/LzFilters.jsx, Tombolo/client-reactjs/src/components/application/clusterMonitoring/ClusterMonitoringFilters.jsx, Tombolo/client-reactjs/src/components/application/costMonitoring/CostMonitoringFilters.jsx, Tombolo/client-reactjs/src/components/application/jobMonitoring/JobMonitoringFilters.jsx, Tombolo/client-reactjs/src/components/common/Monitoring/MonitoringFilters.jsx
Created a shared MonitoringFilters component to ensure a uniform look and functionality to filters and reduce code duplication. The existing Filter files still exist for custom callbacks and functionality.
Fixes #1287 
=> Shared monitoring filters component

Tombolo/client-reactjs/src/components/admin/clusters/clusterUtils.js, Tombolo/server/controllers/clusterController.js, Tombolo/server/migrations/20190423195703-create-cluster.js, Tombolo/server/models/Cluster.js
- Added currencyCode to cluster model and migration
- Fetch currencyCode in GetBuildInfo call in the add cluster route
Fixes #1297 
=> Added cluster currency code

Tombolo/server/jobSchedular/job-scheduler.js
Disabled some bree jobs that are no longer relevant
=> Commented out some bree-jobs that are no longer relevant

tombolo_docs/docs/User-Guides/monitoring/ClusterMonitoring.md, tombolo_docs/docs/User-Guides/monitoring/CostMonitoring.md, tombolo_docs/docs/User-Guides/monitoring/FileMonitoring.md, tombolo_docs/docs/User-Guides/monitoring/LandingZoneMonitoring.md
Modified cluster monitoring, cost monitoring and landingzone monitoring to match the format of job monitoring and file monitoring
=> File monitoring documentation

Tombolo/client-reactjs/package-lock.json, Tombolo/client-reactjs/package.json, Tombolo/client-reactjs/src/components/common/Monitoring/MonitoringDetailsModal.jsx, Tombolo/client-reactjs/src/tests/common/Monitoring/ApproveRejectModal.test.jsx, Tombolo/client-reactjs/src/tests/common/Monitoring/MonitoringDetailsModal.test.jsx, Tombolo/client-reactjs/src/tests/setupTests.js, Tombolo/client-reactjs/vite.config.js
=> Common components unit tests

Tombolo/client-reactjs/src/tests/application/clusterMonitoring/AddEditModal.test.jsx, Tombolo/client-reactjs/src/tests/application/clusterMonitoring/ClusterMonitoringTable.test.jsx, Tombolo/client-reactjs/src/tests/application/clusterMonitoring/NotificationTab.test.jsx, Tombolo/client-reactjs/src/tests/application/fileMonitoring/AddEditFileMonitoringModal.test.jsx, Tombolo/client-reactjs/src/tests/application/fileMonitoring/FileMonitoringNotificationTab.test.jsx, Tombolo/client-reactjs/src/tests/application/fileMonitoring/FileMonitoringTable.test.jsx
Created basic unit tests for cluster and file monitoring.
Fixes #1278 
=> Frontend monitoring unit tests

Tombolo/server/jobs/costMonitoring/monitorCost.js, Tombolo/server/utils/hpcc-util.js
- Created a getClusters method to allow for retrieving multiple clusters at once and checking credentials and reachability asynchronously
- Implemented it in monitorCost.
Fixes #1347 
=> Bulk get cluster hpcc util

Tombolo/.env.sample, Tombolo/server/config/emailConfig.js, tombolo_docs/docs/Install/Configurations.md
Added username and password to environment variables for SMTP handling. 3rd party providers sometimes require these values.
Fixes #1388 
=> Third party smtp handling

Tombolo/client-reactjs/src/components/login/login.jsx
=> fixed broken registration link

Tombolo/client-reactjs/src/components/admin/apps/AddApplication.jsx, Tombolo/client-reactjs/src/components/login/ForgotPassword.jsx, Tombolo/client-reactjs/src/components/login/ResetPasswordWithToken.jsx, Tombolo/client-reactjs/src/components/login/login.jsx, Tombolo/client-reactjs/src/components/login/register.jsx
Updated anchor tags to use react-router links across auth pages
Fixes #1403
=> Fixed navigation links i auth pages
